dateTime <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
data$Global_active_power <- as.numeric(data$Global_active_power)
data$Global_reactive_power <- as.numeric(data$Global_reactive_power)
data$Voltage <- as.numeric(data$Voltage)
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)


png("C:/Users/HP/Desktop/Coursera-R/plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(dateTime, data$Global_active_power, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(dateTime, data$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(dateTime, data$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(dateTime, data$Sub_metering_2, type="l", col="red")
lines(dateTime, data$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(dateTime, data$Global_reactive_power, type="l", xlab="datetime", ylab="Global reactive power")

dev.off()