data <- read.table(file = "C:/Users/HP/Desktop/Coursera-R/household_power_consumption.txt" , header = TRUE , sep = ";")
names(data) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
data <- subset(data , Date %in% c("1/2/2007" , "2/2/2007"))
data$Global_active_power <- as.numeric(data$Global_active_power)
png("C:/Users/HP/Desktop/Coursera-R/plot1.png", width=480, height=480)
hist(data$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off() 